# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6aeb240199d019e31471b6baef25856fa469eaea815ae8651fc7f2fe442571461dee21e59e3c9ec80ac6d949cb98771aafad9fc5c2b8da4372891939860554

test:
  secret_key_base: b26d7310405790d18c663cbe2e37e54a5ca9b77ca62fcfb5ed71bebf9a240adf541d222d51a5af7171d3bdc8681e817e503a0c842ff3ee9e725674ca14192c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
